name: continuous-integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Solution
      shell: cmd
      working-directory: ${{github.workspace}}
      run: build\build_verbose.cmd
  # temporarily disabled pending resolution of:
  # https://github.com/winsiderss/systeminformer/issues/2109
  # https://github.com/actions/runner-images/issues/10012
  #build_driver:
  #  runs-on: windows-latest
  #  steps:
  #  - uses: actions/checkout@v4
  #  - name: Build Driver
  #    shell: cmd
  #    working-directory: ${{github.workspace}}
  #    run: build\build_zdriver.cmd prefast
